import { Dimensions, StyleSheet } from 'react-native';

const { height, width } = Dimensions.get('screen');

const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: '#fff',
  },
  title: {
    color: '#e85454',
    fontSize: 52,
    textAlign: 'center',
    fontWeight: '700',
    marginTop: height / 5,
    marginBottom: 16,
  },
  introText: {
    color: '#474747',
    fontSize: 28,
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 60,
  },
  startButton: {
    backgroundColor: '#e85454',
    height: 56,
    width: width - 32,
    marginLeft: 16,
    marginRight: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 28,
    padding: 16,
  },
  rateButton: {
    backgroundColor: '#e85454',
    height: 56,
    width: width - 32,
    marginLeft: 16,
    marginRight: 16,
    marginTop: 16,
    marginBottom: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 28,
    padding: 16,
  },
  startButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  why: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    paddingBottom: 30,
  },
  whyTitle: {
    color: '#e85454',
    marginBottom: 8,
    fontWeight: '800',
    fontSize: 16,
  },
  whyText: {
    color: '#474747',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
  },
  instructions: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingBottom: 60,
    paddingLeft: 16,
    paddingRight: 16,
  },
  answerContainer: {
    flex: 1,
    margin: 16,
  },
  answerPromptText: {
    color: '#e85454',
    fontWeight: '700',
    fontSize: 18,
    paddingTop: 16,
    paddingBottom: 16,
  },
  answer: {
    flex: 1,
  },
  answerText: {
    fontSize: 16,
    color: '#474747',
    lineHeight: 24,
    minHeight: 40,
  },
  footer: {
    alignItems: 'center',
    flexShrink: 0,
    flexDirection: 'row',
    padding: 16,
  },
  backButton: {
    backgroundColor: '#f0f0f0',
    borderRadius: 28,
    flexShrink: 0,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
    paddingLeft: 16,
    paddingRight: 16,
  },
  backButtonText: {
    color: '#e85454',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  finishExerciseButton: {
    backgroundColor: '#e85454',
    flex: 1,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 16,
    padding: 8,
  },
  finishExerciseButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  past: {
    alignItems: 'center',
    marginTop: 30,
  },
  pastTitle: {
    textAlign: 'center',
    color: '#e85454',
    fontSize: 24,
    fontWeight: '800',
    marginTop: 30,
    marginBottom: 15,
  },
  pastExercises: {
    flex: 1,
    justifyContent: 'flex-start',
    width,
  },
  pastExercise: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginLeft: 16,
    marginRight: 16,
  },
  pastExerciseButton: {
    flex: 4,
    padding: 16,
    borderRadius: 28,
  },
  pastExerciseText: {
    color: '#474747',
    fontSize: 20,
    fontWeight: '700',
  },
  deletePastExerciseButton: {
    paddingTop: 8,
    paddingBottom: 8,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deletePastExerciseButtonText: {
    color: '#e85454',
    fontSize: 16,
    textAlign: 'center',
  },
  takeAgainButton: {
    backgroundColor: '#f0f0f0',
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 16,
    marginBottom: 40,
    width: width - 32,
  },
  takeAgainButtonText: {
    color: '#e85454',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  share: {
    alignItems: 'center',
    padding: 16,
    justifyContent: 'center',
  },
  shareTitleView: {
    marginBottom: 40,
  },
  shareTitle: {
    color: '#474747',
    textAlign: 'center',
    fontWeight: '500',
    fontSize: 20,
    marginBottom: 5,
  },
  shareTitleMain: {
    color: '#e85454',
    fontSize: 24,
    textAlign: 'center',
    fontWeight: '800',
  },
  shareButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  shareButton: {
    backgroundColor: '#e85454',
    width: width / 5,
    justifyContent: 'center',
    alignItems: 'center',
    color: '#fff',
    height: width / 5,
    borderRadius: width / 10,
    margin: 5,
  },
});

export default styles;
